services:
  napcat-zx:
    image: mlikiowa/napcat-docker:latest
    container_name: napcat-zx
    restart: always
    environment:
      - ACCOUNT=3541219424
    volumes:
      - ./napcat-config:/app/config
      - /home/zx/.cache:/home/zx/.cache
      - /home/zx/.local/share/nonebot2:/home/zx/.local/share/nonebot2
    ports:
      - "6100:6099"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"  # 单个日志最大 100MB
        max-file: "3"     # 最多保留 3 个旧日志  