/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-120254-g0a5ae743ef-20250712"
#endif /* AVUTIL_FFVERSION_H */
